apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: test-secrets
spec:
  provider: alibabacloud # please using fixed value 'alibabacloud'
  parameters:
    objects:
      | # objectType support kms and oos, default is kms, replace {kms-instance-id} with the actual KMS service instance id
      - objectName: "test-hangzhou"
        objectType: "kms"
        objectAlias: "hangzhou-public"
        kmsEndpoint:  "kms.cn-hangzhou.aliyuncs.com"
      - objectName: "test-hangzhou"
        objectType: "kms"
        objectAlias: "hangzhou-vpc"
      - objectName: "test-hangzhou"
        objectType: "kms"
        objectAlias: "hangzhou-cryptoservice"
        kmsEndpoint:  "kst-{kms-instance-id}.cryptoservice.kms.aliyuncs.com"
      - objectName: "test-london"
        objectType: "kms"
        objectAlias: "london-public"
        kmsEndpoint:  "kms.eu-west-1.aliyuncs.com"
      - objectName: "test-oos"
        objectType: "oos"
